var quizLessonBoth = "lesson";var lessonNumber = 61;var numOfAllQuiz = 63;var lessonTitle = "Los pronombres interrogativos II (Interrogative pronouns )";var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var quesToRemove = [];var startNarration = ["The use of "+'"'+"what"+'"'+" in Spanish is interesting because in most cases, it can be translated by "+'"'+"qué"+'"'+".","However, the Spanish word "+'"'+"cuál"+'"'+" is also used a lot.","In general terms, "+'"'+"cuál"+'"'+" means "+'"'+"which"+'"'+" or "+'"'+"which one"+'"'+", but can also mean "+'"'+"what"+'"'+" in some situations.","First remember that in most cases, "+'"'+"what"+'"'+" can be translated by "+'"'+"qué"+'"'+"."];var narration = ["","Cuál = What (used with the verb "+'"'+"ser"+'"'+")<br>Cuáles = What (used with the verb "+'"'+"ser"+'"'+")","","",""];var titleSkip = [false,false,false,true];var forTitles = ["Qué","Cuál","Cuáles"];var engTitles = ["What","What (singular)","What (plural)"];var forSideTitles = ["Qué","Cuál","Cuáles"];var engSideTitles = ["What","What (singular)","What (plural)"];var exampleNums = [5,4,3];var forExamples = ["¿<strong>Qué</strong> hiciste hoy?","¿<strong>Qué</strong> comes?","¿<strong>Qué</strong> escuchas?","¿<strong>Qué</strong> está haciendo ella?","¿<strong>En qué</strong> piensas?","¿<strong>Cuál es</strong> el camino correcto?","¿<strong>Cuál es</strong> tu nombre?","¿<strong>Cuál es</strong> tu profesión?","¿<strong>Cuál era</strong> la respuesta?","¿<strong>Cuáles son</strong> los ingredientes?","¿<strong>Cuáles son</strong> las diferencias?","¿<strong>Cuáles son</strong> los cursos disponibles?"];var engExamples = ["<em>What</em> did you do today?","<em>What</em> are you eating?","<em>What</em> are you listening to?","<em>What</em> is she doing?","<em>What</em> are you thinking <em>of</em>?","<em>What is</em> the right path to take?","<em>What is</em> your name?","<em>What is</em> your profession?","<em>What was</em> the answer?","<em>What are</em> the ingredients?","<em>What are</em> the differences?","<em>What are</em> the courses available?"];

var forExtra1 = ["¿<strong>Qué</strong> desea beber?","¿<strong>Qué</strong> le gustaría?","¿<strong>Qué</strong> hace en la vida?","¿<strong>Qué</strong> puedo hacer por usted?","¿<strong>Qué</strong> te gustaría hacer?","¿<strong>Qué</strong> es aquello?","¿A <strong>qué</strong> hora llegará?","¿Y tú? ¿<strong>Qué</strong> has hecho?","¿<strong>Qué</strong> hiciste anoche?","Entonces, ¿a <strong>qué</strong> hora llegamos?","¿<strong>Qué</strong> piensas de este lugar?","¿Mediano? ¿Sabe <strong>qué</strong> número?","¿<strong>Qué</strong> tipo de música te gusta?"];

var engExtra1 = ["<em>What</em> do you want to drink?","<em>What</em> would you like?","<em>What</em> do you do for a living?","<em>What</em> can I do for you?","<em>What</em> would you like to do?","<em>What</em> is that over there?","<em>What</em> time will you be arriving?","And you? <em>What</em> have you been up to?","<em>What</em> did you do last night?","<em>What</em> time do we arrive then?","<em>What</em> do you think of this place?","Medium? Do you know <em>what</em> number?","<em>What</em> kind of music do you like?"];

var imageExtra1 = ["../../verb/40/images/pic1.jpg","../../vocab/41/images/pic12.jpg","../../convo/images/convo13A.jpg","../../convo/images/convo19A.jpg","../../convo/images/convo55B.jpg","../../block/49/images/pic7.jpg","../../convo/images/convo5A.jpg","../../convo/images/convo2B.jpg","../../verb/38/images/pic3.jpg","../../convo/images/convo32B.jpg","../../convo/images/convo40A.jpg","../../convo/images/convo45B.jpg","../../convo/images/convo12B.jpg"];

var fastExtra1 = ["../../verb/40/sounds/sound3","../../vocab/41/sounds/sound17","../../convo/13/sounds/1fast1","../../convo/19/sounds/1fast1","../../convo/55/sounds/2fast7","../../block/49/sounds/sound13","../../convo/5/sounds/1fast12","../../convo/2/sounds/2fast6","../../verb/38/sounds/sound11","../../convo/32/sounds/2fast5","../../convo/40/sounds/1fast2","../../convo/45/sounds/2fast4","../../convo/12/sounds/2fast7"];

var slowExtra1 = ["../../verb/40/sounds/sound4","../../vocab/41/sounds/sound18","../../convo/13/sounds/1slow1","../../convo/19/sounds/1slow1","../../convo/55/sounds/2slow7","../../block/49/sounds/sound14","../../convo/5/sounds/1slow12","../../convo/2/sounds/2slow6","../../verb/38/sounds/sound12","../../convo/32/sounds/2slow5","../../convo/40/sounds/1slow2","../../convo/45/sounds/2slow4","../../convo/12/sounds/2slow7"];



var forExtra2 = ["¿<strong>Cuál</strong> <em>es</em> el pronóstico para mañana?","¿<strong>Cuál</strong> <em>es</em> el precio de este auto?","¿<strong>Cuál</strong> <em>es</em> la dirección del hotel?","¿<strong>Cuál</strong> <em>fue</em> el puntaje final del partido?","¿<strong>Cuál</strong> <em>es</em> la mejor manera para desplazarse en la ciudad?","¿<strong>Cuál</strong> <em>es</em> tu razón para aprender español?"];

var engExtra2 = ["<em>What is</em> the forecast for tomorrow? <i class='qhint'>(singular)</i>","<em>What is</em> the price of this car? <i class='qhint'>(singular)</i>","<em>What is</em> the address of the hotel? <i class='qhint'>(singular)</i>","<em>What was</em> the final score of the game? <i class='qhint'>(singular)</i>","<em>What is</em> the best way to get around (in the city)? <i class='qhint'>(singular)</i>","<em>What is</em> your reason for learning Spanish? <i class='qhint'>(singular)</i>"];var imageExtra2 = ["../../convo/images/convo14B.jpg","../../vocab/90/images/pic6.jpg","../../vocab/90/images/pic1.jpg","../../vocab/90/images/pic11.jpg","../../convo/images/convo17B.jpg","../../vocab/89/images/pic7.jpg"];var fastExtra2 = ["../../convo/14/sounds/2fast5","../../vocab/90/sounds/sound19","../../vocab/90/sounds/sound1","../../vocab/90/sounds/sound39","../../convo/17/sounds/2fast5","../../vocab/89/sounds/sound25"];var slowExtra2 = ["../../convo/14/sounds/2slow5","../../vocab/90/sounds/sound20","../../vocab/90/sounds/sound2","../../vocab/90/sounds/sound40","../../convo/17/sounds/2slow5","../../vocab/89/sounds/sound26"];

var forExtra3 = ["¿<strong>Cuáles</strong> <em>son</em> sus calificaciones?","Y aparte de eso, ¿<strong>cuáles</strong> <em>son</em> tus pasatiempos?"];



var engExtra3 = ["<em>What are</em> your qualifications? <i class='qhint'>(plural)</i>","And other than that, <em>what are</em> your hobbies? <i class='qhint'>(plural)</i>"];var imageExtra3 = ["../../convo/images/convo37A.jpg","../../convo/images/convo12B.jpg"];var fastExtra3 = ["../../convo/37/sounds/1fast4","../../convo/12/sounds/2fast5"];var slowExtra3 = ["../../convo/37/sounds/1slow4","../../convo/12/sounds/2slow5"];