var quizLessonBoth = "both";var lessonNumber = 3;var numOfAllQuiz = 3;var lessonTitle = "Los artículos indefinidos (Indefinite articles)";var btnColor = ["#00BFFF","#001E51","#0066FF","#00025B"];var quesToRemove = [];var startNarration = [];
var narration = ["Un = A / An (masculine singular)","Una = A / An (feminine singular)","Unos = Some (masculine plural)<br>Unas = Some (feminine plural)","",""];var titleSkip = [false,false,false,false];var forTitles = ["Un","Una","Unos","Unas"];var engTitles = ["A / An (masculine)","A / An (feminine)","Some (masculine)","Some (feminine)"];var forSideTitles = ["Un","Una","Unos","Unas"];var engSideTitles = ["A / An (masculine)","A / An (feminine)","Some (masculine)","Some (feminine)"];var exampleNums = [4,4,2,2];var forExamples = ["<strong>Un</strong> hombre","<strong>Un</strong> niño","<strong>Un</strong> avión","Hay <strong>un</strong> muchacho en la piscina.","<strong>Una</strong> mujer","<strong>Una</strong> naranja","<strong>Una</strong> silla","Hay <strong>una</strong> persona en la sala.","<strong>Unos</strong> bomberos","<strong>Unos</strong> hermanos","<strong>Unas</strong> muchachas","<strong>Unas</strong> frutas"];var engExamples = ["<em>A</em> man","<em>A</em> child","<em>A</em> plane","There is <em>a</em> boy in the pool.","<em>A</em> woman","<em>An</em> orange","<em>A</em> chair","There is <em>a</em> person in the room.","<em>Some</em> firefighters","<em>Some</em> brothers","<em>Some</em> girls","<em>Some</em> fruit(s)"];var forExtra1 = ["¿Hay <strong>un</strong> problema?","Sí, te enviaré <strong>un</strong> texto.","Tú serías <strong>un</strong> buen chef.","¿Como <strong>un</strong> tipo de correo?","Yo necesitaba <strong>un</strong> buen café.","Hay <strong>un</strong> perro en la casa.","No sé. Estoy <strong>un</strong> poco cansada.","Tú deberías descansar <strong>un</strong> poco.","No, quisiera <strong>un</strong> boleto ida y vuelta.","Habrá <strong>un</strong> edificio allá.","El perro fue arrollado por <strong>un</strong> autobús.","¿Necesita <strong>un</strong> sobre?","Sí, pero tiene <strong>un</strong> costo adicional.","Yo descansaba en <strong>un</strong> colchón inflable."];var engExtra1 = ["Is there <em>a</em> problem? <i class='qhint'>(masculine)</i>","Yes, I'll send you <em>a</em> text. <i class='qhint'>(masculine)</i>","You would be <em>a</em> good chef. <i class='qhint'>(masculine)</i>","Like <em>a</em> kind of post office? <i class='qhint'>(masculine)</i>","I needed <em>a</em> good coffee. <i class='qhint'>(masculine)</i>","There is <em>a</em> dog in the house. <i class='qhint'>(masculine)</i>","I don't know. I'm <em>a</em> little tired. <i class='qhint'>(masculine)</i>","You should rest <em>a</em> little. <i class='qhint'>(masculine)</i>","No, I would like <em>a</em> round trip. <i class='qhint'>(masculine)</i>","There will be <em>a</em> building over there. <i class='qhint'>(masculine)</i>","The dog got hit by <em>a</em> bus. <i class='qhint'>(masculine)</i>","Do you need <em>an</em> envelope? <i class='qhint'>(masculine)</i>","Yes, but for <em>an</em> additional cost. <i class='qhint'>(masculine)</i>","I was resting on <em>an</em> inflatable mattress. <i class='qhint'>(masculine)</i>"];

var imageExtra1 = ["../../block/64/images/pic10.jpg","../../convo/images/convo4B.jpg","../../verb/6/images/pic4.jpg","../../convo/images/convo52B.jpg","../../verb/74/images/pic4.jpg","../../block/64/images/pic1.jpg","../../convo/images/convo39B.jpg","../../verb/22/images/pic2.jpg","../../convo/images/convo29B.jpg","../../block/64/images/pic15.jpg","../../block/18/images/pic2.jpg","../../convo/images/convo18A.jpg","../../convo/images/convo33A.jpg","../../verb/83/images/pic4.jpg"];
var fastExtra1 = ["../../block/64/sounds/sound19","../../convo/4/sounds/2fast10","../../verb/6/sounds/sound15","../../convo/52/sounds/2fast6","../../verb/74/sounds/sound15","../../block/64/sounds/sound1","../../convo/39/sounds/2fast9","../../verb/22/sounds/sound7","../../convo/29/sounds/2fast2","../../block/64/sounds/sound29","../../block/18/sounds/sound3","../../convo/18/sounds/1fast4","../../convo/33/sounds/1fast8","../../verb/83/sounds/sound15"];
var slowExtra1 = ["../../block/64/sounds/sound20","../../convo/4/sounds/2slow10","../../verb/6/sounds/sound16","../../convo/52/sounds/2slow6","../../verb/74/sounds/sound16","../../block/64/sounds/sound2","../../convo/39/sounds/2slow9","../../verb/22/sounds/sound8","../../convo/29/sounds/2slow2","../../block/64/sounds/sound30","../../block/18/sounds/sound4","../../convo/18/sounds/1slow4","../../convo/33/sounds/1slow8","../../verb/83/sounds/sound16"];

var forExtra2 = ["Yo vivo en <strong>una</strong> casa.","No es <strong>una</strong> buena historia.","Parece <strong>una</strong> infección pulmonar.","Ustedes escribían <strong>una</strong> carta.","Ellos cantaban en <strong>una</strong> coral.","Sí. Hay <strong>una</strong> visita cada mañana.","Nosotros vivimos en <strong>una</strong> casa muy bonita.","Ella trae <strong>una</strong> cosa al campo.","Quisiera <strong>una</strong> habitación en la planta baja.","¿Hay <strong>una</strong> conexión inalámbrica aquí?","Estoy comiendo <strong>una</strong> manzana.","Es <strong>una</strong> vista increíble.","Me gustaría mandarle a hacer <strong>una</strong> radiografía."];var engExtra2 = ["I live in <em>a</em> house. <i class='qhint'>(feminine)</i>","It's not <em>a</em> good story. <i class='qhint'>(feminine)</i>","It looks like <em>a</em> lung infection. <i class='qhint'>(feminine)</i>","You were writing <em>a</em> letter. <i class='qhint'>(feminine)</i>","They used to sing in <em>a</em> choir. <i class='qhint'>(feminine)</i>","Yes. There is <em>a</em> tour every morning. <i class='qhint'>(feminine)</i>","We live in <em>a</em> very nice house. <i class='qhint'>(feminine)</i>","She is bringing <em>a</em> thing in the field. <i class='qhint'>(feminine)</i>","I would like <em>a</em> room on the ground floor. <i class='qhint'>(feminine)</i>","Is there <em>a</em> wireless connection here? <i class='qhint'>(feminine)</i>","I am eating <em>an</em> apple. <i class='qhint'>(feminine)</i>","It's <em>an</em> amazing view. <i class='qhint'>(feminine)</i>","I would like to send you for <em>an</em> x-ray. <i class='qhint'>(feminine)</i>"];

var imageExtra2 = ["../../block/26/images/pic2.jpg","../../block/65/images/pic5.jpg","../../verb/4/images/pic10.jpg","../../block/73/images/pic5.jpg","../../verb/88/images/pic4.jpg","../../convo/images/convo17A.jpg","../../verb/68/images/pic2.jpg","../../vocab/40/images/pic11.jpg","../../convo/images/convo5B.jpg","../../block/64/images/pic11.jpg","../../verb/42/images/pic2.jpg","../../vocab/90/images/pic14.jpg","../../convo/images/convo22A.jpg"];var fastExtra2 = ["../../block/26/sounds/sound3","../../block/65/sounds/sound9","../../convo/20/sounds/1fast8","../../block/73/sounds/sound9","../../verb/88/sounds/sound15","../../convo/17/sounds/1fast3","../../verb/68/sounds/sound7","../../vocab/40/sounds/sound43","../../convo/5/sounds/2fast3","../../block/64/sounds/sound21","../../verb/42/sounds/sound7","../../vocab/90/sounds/sound47","../../convo/22/sounds/1fast4"];var slowExtra2 = ["../../block/26/sounds/sound4","../../block/65/sounds/sound10","../../convo/20/sounds/1slow8","../../block/73/sounds/sound10","../../verb/88/sounds/sound16","../../convo/17/sounds/1slow3","../../verb/68/sounds/sound8","../../vocab/40/sounds/sound44","../../convo/5/sounds/2slow3","../../block/64/sounds/sound22","../../verb/42/sounds/sound8","../../vocab/90/sounds/sound48","../../convo/22/sounds/1slow4"];


var forExtra3 = ["Compré <strong>unos</strong> zapatos nuevos.","¡Hola! ¡Estoy buscando <strong>unos</strong> zapatos!","No. Le voy a prescribir <strong>unos</strong> antibióticos."];
var engExtra3 = ["I bought <em>some</em> new shoes. <i class='qhint'>(masculine)</i>","Hello! I am looking for <em>some</em> shoes! <i class='qhint'>(masculine)</i>","No. I'm going to prescribe you <em>some</em> antibiotics. <i class='qhint'>(masculine)</i>"];
var imageExtra3 = ["../../vocab/92/images/pic12.jpg","../../convo/images/convo45A.jpg","../../convo/images/convo20A.jpg"];
var fastExtra3 = ["../../vocab/92/sounds/sound47","../../convo/45/sounds/1fast1","../../convo/20/sounds/1fast9"];
var slowExtra3 = ["../../vocab/92/sounds/sound48","../../convo/45/sounds/1slow1","../../convo/20/sounds/1slow9"];