var quizLessonBoth = "quiz";
var lessonNumber = 45;
var lessonTitle = "Los pronombres posesivos (Possessive pronouns)";
var btnColor = ["#F30101","#5F0000","#FFEE00","#B83D00"];
////INCLUDE NUMBER IN LIST BELOW TO REMOVE QUESTION
var quesToRemove = [];
////LESSON CONTENT BELOW
var forExamples1 = ["Tu perro es negro y <strong>el mío</strong> es blanco.","Tu casa es rosa, <strong>la mía</strong> es verde.","Este pedazo de pizza <em>es</em> <strong>mío</strong>.","Estos animales <em>son</em> <strong>míos</strong>.","Me gusta mi auto, pero <strong>el tuyo</strong> es más bonito.","Mi caja es roja, <strong>la tuya</strong> es verde.","¿Todos estos zapatos <em>son</em> <strong>tuyos</strong>?","Este paquete <em>es</em> <strong>tuyo</strong>.","Tu gato es gris <strong>el nuestro</strong> es blanco.","Esta aspiradora <em>es</em> <strong>nuestra</strong>.","Esta mesa <em>es</em> <strong>nuestra</strong>.","Estas manzanas <em>son</em> <strong>nuestras</strong>.","Todas las chupetas <em>son</em> <strong>suyas</strong>.","¿Todas las herramientas <em>son</em> <strong>suyas</strong>?","La caja grande es mía, la cajita <em>es</em> <strong>suya</strong>.","El saxofón <em>es</em> <strong>suyo</strong>."];var engExamples1 = ["Your dog is black and <em>mine</em> is white.","Your house is pink, <em>mine</em> is green.","This pizza slice <em>is mine</em>.","These animals <em>are mine</em>.","I love my car, but <em>yours</em> is prettier. (informal)","My box is red, <em>yours</em> is green. (informal)","<em>Are</em> all these shoes <em>yours</em>? (informal)","This package <em>is yours</em>. (informal)","Your cat is grey, <em>ours</em> is white.","This vacuum cleaner <em>is ours</em>.","This table <em>is ours</em>.","These apples <em>are ours</em>.","All these lollipops <em>are his</em>. (unspecified)","<em>Are</em> all those tools <em>his</em>? (unspecified)","The big box is mine, the small box <em>is hers</em>. (unspecified)","This saxophone <em>is hers</em>. (unspecified)"];
var forExamples2 = ["La cámara es <strong>de él</strong>.","El avión es <strong>de él</strong>.","Estos juguetes son <strong>de ella</strong>.","Esta computadora es <strong>de ella</strong>.","¿Esta sierra es <strong>de usted</strong>?","¿Esta ropa es <strong>de usted</strong>?","Este restaurante es <strong>de usted</strong>.","Este kayak no es <strong>de ustedes</strong>.","Nuestro camión es nuevo, el <strong>de ellos</strong> es viejo.","Mi cuadro es moderno, el <strong>de ellos</strong> es antiguo.","Nuestro terreno es grande, pero el <strong>de ellos</strong> es muy grande.","¿Esta casa es <strong>de ellas</strong>?"];var engExamples2 = ["The camera is <em>his</em>. (to him)","The airplane is <em>his</em>. (to him)","These toys are <em>hers</em>. (to her)","This computer is <em>hers.</em> (to her)","Is this saw <em>yours</em>? (to you formal)","Are these clothes <em>yours</em>? (to you formal)","This restaurant is <em>yours</em>. (to you formal)","This kayak is not <em>yours</em>. (to you plural)","Our truck is new, <em>theirs</em> is old. (to them)","My painting is modern, <em>theirs</em> is antique. (to them)","Our land is large, but <em>theirs</em> is very large. (to them)","Is this house <em>theirs</em>? (to them feminine)"];

var forExtra1 = ["Ese regalo no es <strong>el tuyo</strong>." , "Pues parece que mi trabajo no es tan difícil como <strong>el tuyo</strong>."];var engExtra1 = ["That gift is not <em>yours</em>. (informal)" , "It seems that my work is not as difficult as <em>yours</em>. (informal)"];var imageExtra1 = ["../../block/46/images/pic5.jpg" , "../../convo/images/convo52B.jpg"];var fastExtra1 = ["../../block/46/sounds/sound9" , "../../convo/52/sounds/2fast9"];var slowExtra1 = ["../../block/46/sounds/sound10" , "../../convo/52/sounds/2slow9"];
