var quizLessonBoth = "quiz";
var lessonNumber = 69;
var lessonTitle = "La comparación (Comparison)";
var btnColor = ["#FFEE00","#B83D00","#FFC400","#BB0A00"];
////INCLUDE NUMBER IN LIST BELOW TO REMOVE QUESTION
var quesToRemove = [];
////LESSON CONTENT BELOW
var forExamples1 = ["Él es <strong>más</strong> alto <em>que</em> tú.","Ella gana <strong>más</strong> <em>que</em> él.","Ellos son <strong>más</strong> inteligentes <em>que</em> nosotros.","Estoy <strong>más</strong> motivado <em>que</em> Juan.","Tu auto es <strong>menos</strong> veloz <em>que</em> el mío.","Él es <strong>menos</strong> miedoso <em>que</em> yo.","El caballo marrón es <strong>menos</strong> viejo <em>que</em> el blanco.","Cancún tiene <strong>menos</strong> habitantes <em>que</em> la Ciudad de México.","Ella es <strong>tan</strong> fuerte <em>como</em> yo.","La pelota azul es <strong>tan</strong> pesada <em>como</em> la verde.","Ella tiene <strong>tanto</strong> dinero <em>como</em> él.","Él tiene <em>tanto</em> trabajo <strong>como</strong> ella."];var engExamples1 = ["He is taller (<em>more</em> tall) <em>than</em> you are (you).","She earns <em>more than</em> he does.","They are smarter (<em>more</em> smart) <em>than</em> we are (us).","I am <em>more</em> motivated <em>than</em> Juan.","Your car is <em>not as</em> fast as mine.","He is <em>not as</em> scared as I am (me).","The brown horse is <em>not as</em> old as the white one.","Cancun is <em>not as</em> populated as Mexico City.","She is <em>as</em> strong <em>as</em> I am (me).","The blue ball is <em>as</em> heavy <em>as</em> the green ball.","She has <em>as much</em> money <em>as</em> he does (him).","He has <em>as much</em> work <em>as</em> she does (her)."];
var forExamples2 = ["Diego toca <strong>mejor</strong> la guitarra <em>que</em> Carmen.","La sopa está <strong>mejor</strong> <em>que</em> la última vez.","Él escribe <strong>mejor</strong> <em>que</em> yo.","Es <strong>mejor</strong> <em>que</em> nada.","Tú bailas <strong>peor</strong> <em>que</em> yo.","El equipo rojo es <strong>peor</strong> <em>que</em> el azul.","El auto nuevo es <strong>peor</strong> <em>que</em> el viejo.","La situación es <strong>peor</strong> de lo <em>que</em> ella creía."];var engExamples2 = ["Diego is <em>better</em> at guitar <em>than</em> Carmen.","This soup is <em>better</em> <em>than</em> last time.","He writes <em>better</em> <em>than</em> I can (me).","It's <em>better</em> <em>than</em> nothing.","You are <em>worse</em> at dancing <em>than</em> I am.","The red team is <em>worse than</em> the blue team.","The new car is <em>worse than</em> the old one.","The situation is <em>worse than</em> she thought."];
var forExamples3 = ["Diego es <strong>el más</strong> alto del grupo.","Rosa es <strong>la más</strong> guapa del curso.","Juan es <strong>el</strong> estudiante <strong>más</strong> inteligente de la escuela.","Ella es <strong>la menos</strong> talentosa del grupo.","Petra es <strong>la</strong> persona <strong>menos</strong> interesante de la oficina.","Pepe es <strong>el menos</strong> capaz del grupo.","Este auto es <strong>el mejor</strong>.","Ella es <strong>la mejor</strong> de su equipo.","Ella es <strong>la mejor</strong> cantante de la banda.","Paula es <strong>la peor</strong> estudiante de la universidad.","La señorita Sánchez es <strong>la peor</strong> profesora de la escuela.","Ustedes son <strong>los peores</strong> músicos de la ciudad."];var engExamples3 = ["Diego is the tallest (<em>the most</em> tall) of the group.","Rosa is the prettiest (<em>the most</em> pretty) in the class.","Juan is <em>the most</em> intelligent student in the school.","She is <em>the least</em> talented of the group.","Petra is <em>the least</em> interesting person in the office.","Pepe is <em>the least</em> capable of the group.","This car is <em>the best</em>.","She is <em>the best</em> on her team.","She is <em>the best</em> singer in the band.","Paula is <em>the worst</em> student of the university.","Miss Sanchez is <em>the worst</em> teacher in the school.","You are <em>the worst</em> musicians in the city."];