var quizLessonBoth = "lesson";var lessonNumber = 47;var numOfAllQuiz = 48;var lessonTitle = "Los adjetivos demostrativos II (Demonstrative adjectives)";var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var quesToRemove = [];var startNarration = ["The same rules apply for the plural demonstrative adjectives.",""+'"'+"These"+'"'+" and "+'"'+"those"+'"'+" are translated by three different Spanish words and their feminine variations."];var narration = ["","","","",""];var titleSkip = [false,false,false,true];var forTitles = ["Estos / Estas","Esos / Esas","Aquellos / Aquellas"];var engTitles = ["These","Those","Those (over there)"];var forSideTitles = ["Estos / Estas","Esos / Esas","Aquellos<br>Aquellas"];var engSideTitles = ["These","Those","Those (over there)"];var exampleNums = [4,4,3];var forExamples = ["Me gustan <strong>estos</strong> lentes.","Quiero <strong>estos</strong> zapatos.","Me gusta el olor de <strong>estas</strong> flores.","<strong>Estas</strong> frutas son deliciosas.","<strong>Esos</strong> perros son adorables.","<strong>Esos</strong> caballos corren muy rápido.","Vamos a tomar <strong>esas</strong> canoas.","<strong>Esas</strong> flores son hermosas.","Mira <strong>aquellos</strong> pájaros.","<strong>Aquellas</strong> camisas son blancas.","¿Quieres ir a ver <strong>aquellas</strong> tiendas?"];var engExamples = ["I like <em>these</em> glasses.","I want <em>these</em> shoes.","I like the smell of <em>these</em> flowers.","<em>These</em> fruits are delicious.","<em>Those</em> dogs are adorable.","<em>Those</em> horses run very fast.","We are going to take <em>those</em> canoes.","<em>Those</em> flowers are beautiful.","Look at <em>those</em> birds (<em>over there</em>).","<em>Those</em> shirts (<em>over there</em>) are white.","Do you want to go see <em>those</em> stores <em>over there</em>?"];

var forExtra1 = ["<strong>Estos</strong> juguetes son de ella.","¿Todos <strong>estos</strong> zapatos son tuyos?","<strong>Estas</strong> manzanas son nuestras.","<strong>Estas</strong> flores son para mi madre.","Todas <strong>estas</strong> manzanas son muy similares.","Todo lo que nos pertenece está en <strong>estas</strong> cajas."];

var engExtra1 = ["<em>These</em> toys are hers. <i class='qhint'>(masculine)</i>","Are all <em>these</em> shoes yours? <i class='qhint'>(masculine)</i>","<em>These</em> apples are ours. <i class='qhint'>(feminine)</i>","<em>These</em> flowers are for my mother. <i class='qhint'>(feminine)</i>","All <em>these</em> apples are very similar. <i class='qhint'>(feminine)</i>","Everything we own is in <em>these</em> boxes. <i class='qhint'>(feminine)</i>"];



var imageExtra1 = ["../../block/44/images/pic3.jpg","../../block/43/images/pic7.jpg","../../block/43/images/pic12.jpg","../../block/11/images/pic1.jpg","../../vocab/94/images/pic2.jpg","../../vocab/40/images/pic10.jpg"];var fastExtra1 = ["../../block/44/sounds/sound5","../../block/43/sounds/sound13","../../block/43/sounds/sound23","../../block/11/sounds/sound1","../../vocab/94/sounds/sound7","../../vocab/40/sounds/sound39"];var slowExtra1 = ["../../block/44/sounds/sound6","../../block/43/sounds/sound14","../../block/43/sounds/sound24","../../block/11/sounds/sound2","../../vocab/94/sounds/sound8","../../vocab/40/sounds/sound40"];var forExtra2 = ["¡Pero <strong>esas</strong> son para niños!","<strong>Esas</strong> son unas emociones un tanto locas."];


var engExtra2 = ["But <em>those</em> (las historietas) are for children! <i class='qhint'>(feminine)</i>","<em>Those</em> are somewhat crazy emotions. <i class='qhint'>(feminine)</i>"];var imageExtra2 = ["../../convo/images/convo59A.jpg","../../convo/images/convo49B.jpg"];var fastExtra2 = ["../../convo/59/sounds/1fast4","../../convo/49/sounds/2fast2"];var slowExtra2 = ["../../convo/59/sounds/1slow4","../../convo/49/sounds/2slow2"];